In [1]:
import pandas as pd

In [2]:
text = pd.read_json('all_tweets copy.json')
text.head(1000)

,source,id_str,text,created_at,retweet_count,in_reply_to_user_id_str,favorite_count,is_retweet
0,Twitter for iPhone,1079888205351145472,HAPPY NEW YEAR! https://t.co/bHoPDPQ7G6,2018-12-31 23:53:06+00:00,33548,NaN,136012,False
1,Twitter for iPhone,1079830268708556800,"....Senator Schumer, more than a year longer t...",2018-12-31 20:02:52+00:00,17456,25073877.0,65069,False
2,Twitter for iPhone,1079830267274108928,Heads of countries are calling wanting to know...,2018-12-31 20:02:52+00:00,21030,NaN,76721,False
3,Twitter for iPhone,1079763923845419008,Itâ€™s incredible how Democrats can all use thei...,2018-12-31 15:39:15+00:00,29610,NaN,127485,False
4,Twitter for iPhone,1079763419908243456,"Iâ€™m in the Oval Office. Democrats, come back f...",2018-12-31 15:37:14+00:00,30957,NaN,132439,False
...,...,...,...,...,...,...,...,...
995,Twitter for iPhone,1047319923700060160,"Thank you Mississippi - Together, we are MAKIN...",2018-10-03 02:58:22+00:00,11026,NaN,51047,False
996,Twitter for iPhone,1047309776374259712,"Today, my Administration provided HISTORIC lev...",2018-10-03 02:18:03+00:00,17730,NaN,76326,False
997,Twitter for iPhone,1047309022892707840,â€œNational wage growth is at the highest itâ€™s b...,2018-10-03 02:15:03+00:00,12636,NaN,52131,False
998,Twitter for iPhone,1047296564388147200,GOD BLESS THE U.S.A.! #MAGAðŸ‡ºðŸ‡¸ https://t.co/pqu...,2018-10-03 01:25:33+00:00,21274,NaN,84510,False
999,Twitter for iPhone,1047294700246454272,Thank you Mississippi - I love you! https://t....,2018-10-03 01:18:08+00:00,11406,NaN,51334,False

In [3]:
# text = df['text'].str.lower()
# text[1]

In [4]:
# from stop_words import get_stop_words

# stop_words = get_stop_words('en')
# stop_words = get_stop_words('english')

In [5]:
# stop_words

In [6]:
# for row in text.iteritems():
#     for stop_word in stop_words: 
#         row = row.replace(' ' + stop_word + ' ', ' ') 
    #row
    
# for index, value in text.items():
#     for stop_word in stop_words: 
#         text.replace(index, value.replace(' ' + stop_word + ' ', ' '))

# text[1]

In [7]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [8]:
text['text'] = text['text'].str.lower()

import re
for index, value in text['text'].iteritems():
    text['text'][index] = re.sub(r'https?:\/\/.*[\r\n]*', '', value, flags=re.MULTILINE).strip().lower()
    
text

/Users/emilychin/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,source,id_str,text,created_at,retweet_count,in_reply_to_user_id_str,favorite_count,is_retweet
0,Twitter for iPhone,1079888205351145472,happy new year!,2018-12-31 23:53:06+00:00,33548,NaN,136012,False
1,Twitter for iPhone,1079830268708556800,"....senator schumer, more than a year longer t...",2018-12-31 20:02:52+00:00,17456,25073877.0,65069,False
2,Twitter for iPhone,1079830267274108928,heads of countries are calling wanting to know...,2018-12-31 20:02:52+00:00,21030,NaN,76721,False
3,Twitter for iPhone,1079763923845419008,itâ€™s incredible how democrats can all use thei...,2018-12-31 15:39:15+00:00,29610,NaN,127485,False
4,Twitter for iPhone,1079763419908243456,"iâ€™m in the oval office. democrats, come back f...",2018-12-31 15:37:14+00:00,30957,NaN,132439,False
...,...,...,...,...,...,...,...,...
36302,Twitter Web Client,1773561338,"""my persona will never be that of a wallflower...",2009-05-12 14:07:28+00:00,1421,NaN,1950,False
36303,Twitter Web Client,1741160716,new blog post: celebrity apprentice finale and...,2009-05-08 20:40:15+00:00,8,NaN,27,False
36304,Twitter Web Client,1737479987,donald trump reads top ten financial tips on l...,2009-05-08 13:38:08+00:00,3,NaN,2,False
36305,Twitter Web Client,1701461182,donald trump will be appearing on the view tom...,2009-05-05 01:00:10+00:00,2,NaN,3,False
36306,Twitter Web Client,1698308935,be sure to tune in and watch donald trump on l...,2009-05-04 18:54:25+00:00,253,NaN,202,False

In [9]:
example = text.iloc[0]
print (nltk.word_tokenize(example['text']))

['happy', 'new', 'year', '!']

In [10]:
def identify_tokens(row):
    text = row['text']
    tokens = nltk.word_tokenize(text)
    # taken only words (not punctuation)
    token_words = [w for w in tokens if w.isalpha()]
    return token_words

text['text_tokened'] = text.apply(identify_tokens, axis=1)

In [11]:
# from nltk.stem import PorterStemmer
# stemming = PorterStemmer()

# def stem_list(row):
#     my_list = row['text_tokened']
#     stemmed_list = [stemming.stem(word) for word in my_list]
#     return (stemmed_list)

# text['stemmed_words'] = text.apply(stem_list, axis=1)
# text

In [12]:
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))                  

def remove_stops(row):
    my_list = row['text_tokened']
    meaningful_words = [w for w in my_list if not w in stops]
    return (meaningful_words)

text['token_meaningful'] = text.apply(remove_stops, axis=1)
text

,source,id_str,text,created_at,retweet_count,in_reply_to_user_id_str,favorite_count,is_retweet,text_tokened,token_meaningful
0,Twitter for iPhone,1079888205351145472,happy new year!,2018-12-31 23:53:06+00:00,33548,NaN,136012,False,"[happy, new, year]","[happy, new, year]"
1,Twitter for iPhone,1079830268708556800,"....senator schumer, more than a year longer t...",2018-12-31 20:02:52+00:00,17456,25073877.0,65069,False,"[senator, schumer, more, than, a, year, longer...","[senator, schumer, year, longer, administratio..."
2,Twitter for iPhone,1079830267274108928,heads of countries are calling wanting to know...,2018-12-31 20:02:52+00:00,21030,NaN,76721,False,"[heads, of, countries, are, calling, wanting, ...","[heads, countries, calling, wanting, know, sen..."
3,Twitter for iPhone,1079763923845419008,itâ€™s incredible how democrats can all use thei...,2018-12-31 15:39:15+00:00,29610,NaN,127485,False,"[it, s, incredible, how, democrats, can, all, ...","[incredible, democrats, use, ridiculous, sound..."
4,Twitter for iPhone,1079763419908243456,"iâ€™m in the oval office. democrats, come back f...",2018-12-31 15:37:14+00:00,30957,NaN,132439,False,"[i, m, in, the, oval, office, democrats, come,...","[oval, office, democrats, come, back, vacation..."
...,...,...,...,...,...,...,...,...,...,...
36302,Twitter Web Client,1773561338,"""my persona will never be that of a wallflower...",2009-05-12 14:07:28+00:00,1421,NaN,1950,False,"[my, persona, will, never, be, that, of, a, wa...","[persona, never, wallflower, rather, build, wa..."
36303,Twitter Web Client,1741160716,new blog post: celebrity apprentice finale and...,2009-05-08 20:40:15+00:00,8,NaN,27,False,"[new, blog, post, celebrity, apprentice, final...","[new, blog, post, celebrity, apprentice, final..."
36304,Twitter Web Client,1737479987,donald trump reads top ten financial tips on l...,2009-05-08 13:38:08+00:00,3,NaN,2,False,"[donald, trump, reads, top, ten, financial, ti...","[donald, trump, reads, top, ten, financial, ti..."
36305,Twitter Web Client,1701461182,donald trump will be appearing on the view tom...,2009-05-05 01:00:10+00:00,2,NaN,3,False,"[donald, trump, will, be, appearing, on, the, ...","[donald, trump, appearing, view, tomorrow, mor..."
36306,Twitter Web Client,1698308935,be sure to tune in and watch donald trump on l...,2009-05-04 18:54:25+00:00,253,NaN,202,False,"[be, sure, to, tune, in, and, watch, donald, t...","[sure, tune, watch, donald, trump, late, night..."

In [13]:
def rejoin_words(row):
#     my_list = row['stem_meaningful']
    my_list = row['token_meaningful']
    joined_words = ( " ".join(my_list))
    return joined_words

text['processed'] = text.apply(rejoin_words, axis=1)

In [14]:
text['processed']

0                                           happy new year
1        senator schumer year longer administration his...
2        heads countries calling wanting know senator s...
3        incredible democrats use ridiculous sound bite...
4        oval office democrats come back vacation give ...
                               ...
36302    persona never wallflower rather build walls cl...
36303    new blog post celebrity apprentice finale less...
36304    donald trump reads top ten financial tips late...
36305    donald trump appearing view tomorrow morning d...
36306    sure tune watch donald trump late night david ...
Name: processed, Length: 36307, dtype: object

In [15]:
text.to_json(r'/Users/emilychin/finalproject/static/processed_tweets\Processed_Tweets_Not_Stemmed.json', orient='records')

In [16]:
# text['json'] = text.apply(lambda x: x.to_json(), axis=1)

In [17]:
# text['json'].to_json(r'/Users/emilychin/finalproject/static/processed_tweets\Processed_Tweets_inBetter.json')